Resources:
  OperatorUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: 'kms.user'
  OperatorAccessKey:
    Type: 'AWS::IAM::AccessKey'
    Properties:
      UserName:
        !Ref OperatorUser
  KMSKey:
    Type: 'AWS::KMS::Key'
    Properties:
      Description: "SOPS symmetric encryption KMS key"
      EnableKeyRotation: true
      PendingWindowInDays: 20
      KeyPolicy:
        Version: 2012-10-17
        Id: "sops-key-policy"
        Statement:
          - Sid: Enable Root IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Enable User Permissions
            Effect: Allow
            Principal:
              AWS: !Join
                - ''
                - - 'arn:aws:iam::'
                  - !Ref 'AWS::AccountId'
                  - ':user/kms.user'
            Action:
              - "kms:DescribeKey"
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey"
              - "kms:GenerateDataKeyWithoutPlaintext"
            Resource: '*'
  KMSKeyAlias:
    Type: 'AWS::KMS::Alias'
    Properties:
      AliasName: "alias/sops-key"
      TargetKeyId: !Ref KMSKey
Outputs:
  OperatorAccessKeyOutput:
    Value:
      !Ref OperatorAccessKey
  OperatorSecretKeyOutput:
    Value: !GetAtt OperatorAccessKey.SecretAccessKey
